nelmio_cors:
  defaults:
    allow_origin: ["https://limulusfestival.netlify.app"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600

  paths:
    "^/":
      allow_origin: ["https://limulusfestival.netlify.app"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
