nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST']
        allow_headers: ['Content-Type']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
        allow_origin: ['*']
        allow_headers: ['Content-Type']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        max_age: 3600

